### ISSUE TITLE
Cannot configure client

### ISSUE THREAD

**Issue by colinmollenhour** [tjlytle/FlowTest#1]
On my first attempt to use the flow test I got this: http://screencast.com/t/laU3vl2yPBC

I could not use it since flash could not be configured. However, after I went to http://www.twilio.com/api/client and use their test dialer and saved the permissions it worked. Maybe this is a cross-domain issue? It would be nice if it could work within openvbx without first using the test dialer since my users are not going to be able to figure that out.

Thanks,
Colin

**Comment by tjlytle** [comment]
Anything with client permissions is really an OpenVBX issue. The plugin doesn't use the 'client' directly (it just calls the client, in the same way an incoming call would). 

I'd post the issue to OpenVBX, as (unless I'm completely incorrect) you would have had the same experience if you routed a call flow to the client (browser phone) and tried to answer.
